In [1]:
import sys
sys.path.append('../')
from datetime import datetime
import pytz, os
import numpy as np
import scipy as sp
from tqdm import tqdm
import scqubits as scq
import scqubits.settings as settings
import qutip as qt
from multiprocessing import Pool
from joblib import Parallel, delayed
import pandas as pd
import utils_2Q_gate_zp as ut
# Update scqubits settings
settings.OVERLAP_THRESHOLD = 0.3
max_step, nsteps = 1e-3, 1e4

In [2]:
folder = '../../data/3ncut_one_zeropi/'
evals = scq.read(folder + f'zeropi_0_specdata_truc=1000_3ncut.h5').energy_table
n_theta = scq.read(folder + f'zeropi_0_n_theta_truc=1000_3ncut.h5').matrixelem_table
n_phi = scq.read(folder + f'zeropi_0_n_phi_truc=1000_3ncut.h5').matrixelem_table
evals = evals - evals[0]

In [ ]:
# drive_phi, drive_theta, truc = False, True, 150
drive_phi, drive_theta, truc = True, False, 300
hspace_ntheta = [
0,   1,   2,   4,   5,   7,   8,  11,  12,  16,  17,  18,  21,
23,  25,  27,  30,  31,  32,  33,  37,  38,  40,  41,  42,  45,
46,  47,  48,  51,  52,  56,  59,  62,  63,  64,  65,  67,  72,
73,  74,  76,  78,  79,  82,  83,  85,  87,  88,  90,  92,  93,
96,  97,  98, 102, 103, 106, 107, 112, 114, 118, 119, 120, 121,
122, 123, 124, 127, 128, 131, 132, 133, 134, 137, 138, 142, 143
]
hspace_nphi = [
0,   2,   3,   4,   8,   9,  10,  11,  15,  16,  18,  19,  20,
23,  24,  25,  28,  31,  33,  35,  37,  39,  40,  42,  43,  46,
47,  49,  51,  53,  55,  56,  57,  60,  62,  64,  66,  67,  69,
70,  73,  76,  77,  79,  81,  83,  85,  86,  88,  91,  92,  95,
96,  98, 100, 101, 102, 104, 106, 108, 110, 112, 113, 116, 118,
120, 121, 123, 126, 128, 130, 132, 133, 136, 137, 139, 141, 143,
145, 146, 148, 151, 153, 154, 156, 158, 159, 162, 164, 166, 167,
169, 170, 173, 174, 176, 179, 181, 183, 185, 186, 188, 190, 192,
194, 196, 198, 200, 202, 205, 206, 208, 209, 212, 213, 216, 218,
220, 222, 223, 226, 227, 229, 230, 232, 234, 237, 239, 241, 242,
245, 246, 248, 250, 252, 253, 255, 257, 259, 262, 264, 265, 267,
269, 271, 273, 275, 277, 279, 281, 282, 283, 286, 288, 290, 291,
293, 294, 297, 299
]
hspace = hspace_ntheta if drive_theta else hspace_nphi
idx_2 = hspace.index(2)
hspace_len = len(hspace)

t1_other = 50 # μs
gamma_decay_logi =  1 / 1600e3
gamma_dephase_logi = 1 / 100e3
gamma_decay_other =  1 / 1e3 / t1_other
gamma_dephase_other = 1 / 1e3 / t1_other

if drive_theta:
    gamma_decay   = [0, gamma_decay_other,  gamma_decay_logi]  + [gamma_decay_other]  * (hspace_len-3)
    gamma_dephase = [0, gamma_dephase_other, gamma_dephase_logi] + [gamma_dephase_other] * (hspace_len-3)
else:
    gamma_decay   = [0,  gamma_decay_logi]  + [gamma_decay_other]  * (hspace_len-2)
    gamma_dephase = [0,  gamma_dephase_logi] + [gamma_dephase_other] * (hspace_len-2)

### $T_1$

$\gamma_{ll'} = \Gamma | \bra{l} n_\theta \ket{l'} |^2 = 1/ T_1  $ ( $T_1$ is intrawell decay time )

$\gamma_{07} = \Gamma_{07} | \bra{0} n_\theta \ket{7} |^2 = 1 / (2\times 10^{-6})   $

In [41]:
gamma_decay_0 = []
gamma_decay_2 = []
if drive_theta:
    Gamma_0 = gamma_decay_other / (n_theta[0,7]**2)
    Gamma_2 = gamma_decay_other / (n_theta[2,7]**2)
    for i in hspace:
        gamma_decay_0.append(Gamma_0* n_theta[0, i]**2)
        gamma_decay_2.append(Gamma_2* n_theta[0, i]**2)
else:
    Gamma_0 = gamma_decay_other / (n_phi[0,9]**2)
    Gamma_2 = gamma_decay_other / (n_phi[2,9]**2)
    for i in hspace:
        gamma_decay_0.append(Gamma_0* n_phi[0, i]**2)
        gamma_decay_2.append(Gamma_2* n_phi[0, i]**2)
gamma_decay_0[idx_2] = gamma_decay_logi
gamma_decay_2[idx_2] = gamma_decay_logi
print('np.imag(gamma_decay_0)=0 -->', np.all(np.imag(gamma_decay_0)==0))
print('np.imag(gamma_decay_2)=0 -->', np.all(np.imag(gamma_decay_2)==0))

if np.all(np.imag(gamma_decay_0)==0) and np.all(np.imag(gamma_decay_2)==0):
    gamma_decay_0 = np.real(gamma_decay_0)
    gamma_decay_2 = np.real(gamma_decay_2)
print('t1_other = %d μs'%t1_other)
print('gamma_decay_0=', gamma_decay_0.tolist())
print('gamma_decay_2=', gamma_decay_2.tolist())

np.imag(gamma_decay_0)=0 --> True
np.imag(gamma_decay_2)=0 --> True
t1_other = 50 μs
gamma_decay_0= [9.24878833313939e-35, 6.25e-07, 3.2239785055138662e-09, 3.3321952122994312e-34, 1.3411148909397326e-31, 2e-05, 0.003979646377759893, 4.5202598932261744e-30, 0.00016688438339287914, 3.594659646647095e-31, 5.504119894166018e-33, 8.515757692986305e-07, 4.49727918178021e-05, 6.423085139537547e-31, 1.1467809705056655e-06, 4.129391549948097e-32, 9.839376917210637e-07, 1.6032088897111164e-32, 6.203682171812002e-33, 2.036812279007242e-06, 1.926404244139375e-34, 6.689476042305062e-07, 2.4660713179099276e-32, 1.095794155241281e-32, 3.092905309817979e-07, 2.3194498678504048e-33, 5.4742318259733764e-33, 2.640773869802032e-08, 5.925715850237472e-32, 8.626704686548277e-06, 4.250661693660793e-06, 1.415635672896945e-32, 9.570397211583226e-07, 4.003973371462972e-07, 3.3142573340151597e-31, 1.5311803466866893e-34, 8.919515609567524e-06, 1.5542956781036325e-30, 8.153257700099807e-06, 2.9524973722777175e-09, 6.100137672173446e-33, 1.2606335820354794e-33, 6.515639708782711e-09, 5.705281238528954e-33, 1.446829721303655e-06, 7.469191619994649e-32, 7.018085986532628e-34, 1.6636538208346668e-07, 1.7255673470387224e-32, 8.954696328023406e-08, 3.485442213750807e-33, 8.938582527723568e-09, 1.9109372332423376e-33, 4.600972026679565e-33, 7.447504009517537e-08, 1.9979124977520355e-06, 1.087676875672673e-32, 1.8972775088582274e-08, 5.043185019660289e-34, 5.5464567933995846e-08, 3.564867404433426e-10, 2.0288405172274205e-33, 2.997691285507473e-07, 1.1025404869507196e-08, 3.426811489375313e-37, 7.629917272171941e-34, 1.7655289026547508e-34, 1.7327711748717025e-33, 4.372011334994928e-08, 9.896515603884059e-35, 7.92357043061933e-09, 1.2600815746506348e-35, 1.2478035947076559e-33, 2.917684155629295e-10, 5.683767706485753e-33, 3.817876279459462e-08, 7.968240876122956e-10, 8.469786454655413e-33, 6.800437904672701e-08, 2.8371198426432456e-07, 3.1928301270265427e-10, 5.208780056991042e-34, 1.1047393380364392e-07, 2.913188894268169e-33, 1.990001151962988e-34, 3.9611417830138754e-33, 1.2355684983925535e-08, 1.2797007362005764e-33, 9.131486016310068e-09, 6.389640797841032e-35, 1.3635501501571086e-09, 1.566986272787328e-10, 6.893837764471217e-34, 1.3053816451306897e-08, 8.407871646253864e-33, 7.514451513513286e-35, 3.120328799332327e-36, 3.197300362494486e-09, 1.3828171960664068e-09, 4.363912672950881e-09, 1.549426620781826e-32, 9.07284625704765e-33, 9.310400791000322e-12, 1.8275785023756863e-33, 5.996383197963594e-08, 2.4395570466657134e-33, 2.798439134969865e-09, 2.143435154101385e-09, 1.3679798178484872e-34, 1.957316231313377e-08, 6.254374000038588e-36, 2.939283900551858e-34, 4.729106695595296e-12, 1.3016617513330954e-09, 2.6885177081110937e-33, 1.0243851894947294e-10, 2.1179689846091717e-34, 1.6630937796525208e-34, 1.0458825209556743e-35, 3.385889706440988e-09, 5.8003644470774325e-34, 2.5542388696044515e-11, 2.0603502847379388e-11, 1.3707675533787596e-33, 1.0307620308826566e-34, 6.509149714916989e-10, 4.300215832317381e-36, 3.425179594624073e-11, 6.994914515676503e-09, 4.768048781632935e-34, 5.528243603355762e-12, 5.485932114385906e-35, 9.818716018489597e-34, 1.4082247904004751e-09, 3.7608583661580965e-34, 2.1304518474247707e-14, 4.956815151389592e-09, 1.6387935387944777e-09, 3.0246250259247367e-35, 2.062806901420703e-34, 3.697995735982144e-38, 1.3956294077163846e-10, 9.201132754888818e-12, 1.2579281034949978e-10, 2.2700563662433078e-36, 9.96911248148179e-10, 1.8395878396817477e-34, 7.268317711063813e-11, 9.192595938472948e-33, 1.061720039060432e-34, 9.867174546191454e-10, 3.1221455428055833e-35, 4.1162731789842193e-10, 7.0875398772709405e-34, 2.1136861039398658e-36, 7.557264527744546e-12, 1.235727012308134e-11, 3.013902333040517e-36, 2.4154667564306944e-38, 7.283441848575265e-36]
gamma_decay_2= [5.658905852751062e-34, 6.25e-07, 1.9726033483353887e-08, 2.0388161465243178e-33, 8.20566179286144e-31, 0.00012237075060901983, 0.024349615720247245, 2.7657379804096737e-29, 0.001021088363035503, 2.1994059957207947e-30, 3.367716414455671e-32, 5.210398304476345e-06, 0.0002751677145863814, 3.929988748754252e-30, 7.0166224072459245e-06, 2.5265837176284615e-31, 6.020259694420645e-06, 9.809293760850128e-32, 3.7957462195221435e-32, 1.2462312371589223e-05, 1.1786776666586836e-33, 4.092981022389628e-06, 1.5088749911400626e-31, 6.704657664492617e-32, 1.8924057216252452e-06, 1.4191641066442293e-32, 3.3494292877607357e-32, 1.615767403181803e-07, 3.625671482446627e-31, 5.278281638876308e-05, 2.6007833101913932e-05, 8.661619994065199e-32, 5.855683452039548e-06, 2.449846134422258e-06, 2.02784078837442e-30, 9.368584417091468e-34, 5.4574391010582334e-05, 9.510016439894848e-30, 4.988601323349919e-05, 1.8064965980839144e-08, 3.732392128811117e-32, 7.713233883830948e-33, 3.986618609308378e-08, 3.4907977379717314e-32, 8.85248194996836e-06, 4.570052924906729e-31, 4.2940422500532046e-33, 1.0179128340455096e-06, 1.0557948574177171e-31, 5.478964555680288e-07, 2.1325808995052496e-32, 5.4691052664910123e-08, 1.1692141179929421e-32, 2.8151220021794074e-32, 4.556783279041728e-07, 1.2224302600052908e-05, 6.654991784806925e-32, 1.1608563643629626e-07, 3.085691681579969e-33, 3.3936204051440213e-07, 2.1811775005107325e-09, 1.2413536847955572e-32, 1.8341486635083347e-06, 6.745935348249688e-08, 2.096707470752351e-36, 4.668393518402027e-33, 1.0802454851989046e-33, 1.0602025465136167e-32, 2.6750315436723604e-07, 6.055220214305845e-34, 4.848066305491608e-08, 7.70985640592969e-35, 7.634733124850449e-33, 1.785196000822005e-09, 3.477634602649843e-32, 2.335981930249131e-07, 4.8753980852231985e-09, 5.182270629771458e-32, 4.1608734543241415e-07, 1.7359024235599906e-06, 1.9535450960566503e-09, 3.1870116266564336e-33, 6.759389101141536e-07, 1.7824455582872815e-32, 1.2175896733926248e-33, 2.423639466280795e-32, 7.559872228857813e-08, 7.829896982188988e-33, 5.587133989958155e-08, 3.909525702769116e-34, 8.342932768388354e-09, 9.58766431975078e-10, 4.21802050907575e-33, 7.98702658729398e-08, 5.144387821881902e-32, 4.597745360618528e-34, 1.9091848866061924e-35, 1.9562802264047067e-08, 8.460818911885315e-09, 2.6700763469060667e-08, 9.480224929933456e-32, 5.551255033175784e-32, 5.696603666327606e-11, 1.118210765663105e-32, 3.668909564370598e-07, 1.4926521347700344e-32, 1.7122354873995925e-08, 1.3114688434457327e-08, 8.370035856405478e-34, 1.197591282025179e-07, 3.826762204871298e-35, 1.798411885817692e-33, 2.8935216802506888e-11, 7.964266277484109e-09, 1.644979649835981e-32, 6.267739227561652e-10, 1.2958872720662395e-33, 1.0175701707463538e-33, 6.399271456909988e-35, 2.0716693242826874e-08, 3.5489747559736876e-33, 1.562820638541155e-10, 1.2606330543044462e-10, 8.387092720872422e-33, 6.306756170919418e-34, 3.982647682204396e-09, 2.631103195907344e-35, 2.09570898982423e-10, 4.27986469864631e-08, 2.917348541744223e-33, 3.382476596460785e-11, 3.356588153137652e-34, 6.007618245996892e-33, 8.616276231376787e-09, 2.3010953060048905e-33, 1.3035249585287108e-13, 3.0328459535285326e-08, 1.0027019771774603e-08, 1.85062817366618e-34, 1.2621361444415888e-33, 2.2626325698054478e-37, 8.539210909713785e-10, 5.6297476083449146e-11, 7.696680311843182e-10, 1.3889425073098875e-35, 6.099638886323373e-09, 1.1255587237654032e-33, 4.447147469838558e-10, 5.624524325181808e-32, 6.496173905823145e-34, 6.037267778038313e-09, 1.910296467918624e-34, 2.5185571931203752e-09, 4.3365378737650254e-33, 1.29326677545488e-35, 4.6239406640550985e-11, 7.56084210219939e-11, 1.84406745378222e-35, 1.4779124002777925e-37, 4.45640123013651e-35]

In [ ]:
folder_1 = 'data/data_xgate_gamma_'
folder_2 = f'theta.txt' if drive_theta else f'phi.txt'
gamma_new = pd.read_csv(folder_1 + folder_2)
# gamma_decay_07 = gamma_new['gamma_decay_07'].to_numpy()
# gamma_decay_27 = gamma_new['gamma_decay_27'].to_numpy()
# gamma_decay_09 = gamma_new['gamma_decay_09'].to_numpy()
# gamma_decay_29 = gamma_new['gamma_decay_29'].to_numpy()
# hspace_ntheta = gamma_new['hspace_ntheta'].to_numpy()
# hspace_nphi = gamma_new['hspace_nphi'].to_numpy()
# g = np.column_stack((hspace_ntheta, hspace_nphi, gamma_decay_07, gamma_decay_27, gamma_decay_09, gamma_decay_29))
# df = pd.DataFrame(g, columns=['hspace_ntheta', 'hspace_nphi' ,'gamma_decay_07', 'gamma_decay_27','gamma_decay_09', 'gamma_decay_29',])
# gamma_new['gamma_decay_old'] = gamma_decay
# gamma_new['gamma_dephase_old'] = gamma_dephase
# gamma_new.to_csv(folder_1 + folder_2 , index=False)

In [38]:
desired_order = ['hspace', 'gamma_dephase_old', 'derivative', 'gamma_dephase',
                 'decay_2us_old', 'decay_2us_0', 'decay_2us_2', ]
gamma_new = gamma_new.reindex(columns=desired_order)
gamma_new

,hspace,gamma_dephase_old,derivative,gamma_dephase,decay_2us_old,decay_2us_0,decay_2us_2
0,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,2.312197e-33,1.414726e-32
1,2.0,0.000111,1.816109,1.111111e-04,6.250000e-07,6.250000e-07,6.250000e-07
2,3.0,0.000500,1.816056,7.988605e-06,5.000000e-04,8.059946e-08,4.931508e-07
3,4.0,0.000500,0.000271,1.190838e-09,5.000000e-04,8.330488e-33,5.097040e-32
4,8.0,0.000500,0.110984,4.882067e-07,5.000000e-04,3.352787e-30,2.051415e-29
...,...,...,...,...,...,...,...
155,291.0,0.000500,0.202705,8.916755e-07,5.000000e-04,1.889316e-10,1.155985e-09
156,293.0,0.000500,0.016108,7.085858e-08,5.000000e-04,3.089318e-10,1.890211e-09
157,294.0,0.000500,0.259940,1.143443e-06,5.000000e-04,7.534756e-35,4.610169e-34
158,297.0,0.000500,0.016562,7.285540e-08,5.000000e-04,6.038667e-37,3.694781e-36
159,299.0,0.000500,0.008101,3.563526e-08,5.000000e-04,1.820860e-34,1.114100e-33

In [42]:
gamma_new['decay_50us_old'] = gamma_decay
gamma_new['decay_50us_0'] = gamma_decay_0
gamma_new['decay_50us_2'] = gamma_decay_2
gamma_new

,hspace,gamma_dephase_old,derivative,gamma_dephase,decay_2us_old,decay_2us_0,decay_2us_2,decay_5us_old,decay_5us_0,decay_5us_2,decay_50us_old,decay_50us_0,decay_50us_2
0,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,2.312197e-33,1.414726e-32,0.000000e+00,9.248788e-34,5.658906e-33,0.000000e+00,9.248788e-35,5.658906e-34
1,2.0,0.000111,1.816109,1.111111e-04,6.250000e-07,6.250000e-07,6.250000e-07,6.250000e-07,6.250000e-07,6.250000e-07,6.250000e-07,6.250000e-07,6.250000e-07
2,3.0,0.000500,1.816056,7.988605e-06,5.000000e-04,8.059946e-08,4.931508e-07,2.000000e-04,3.223979e-08,1.972603e-07,2.000000e-05,3.223979e-09,1.972603e-08
3,4.0,0.000500,0.000271,1.190838e-09,5.000000e-04,8.330488e-33,5.097040e-32,2.000000e-04,3.332195e-33,2.038816e-32,2.000000e-05,3.332195e-34,2.038816e-33
4,8.0,0.000500,0.110984,4.882067e-07,5.000000e-04,3.352787e-30,2.051415e-29,2.000000e-04,1.341115e-30,8.205662e-30,2.000000e-05,1.341115e-31,8.205662e-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,291.0,0.000500,0.202705,8.916755e-07,5.000000e-04,1.889316e-10,1.155985e-09,2.000000e-04,7.557265e-11,4.623941e-10,2.000000e-05,7.557265e-12,4.623941e-11
156,293.0,0.000500,0.016108,7.085858e-08,5.000000e-04,3.089318e-10,1.890211e-09,2.000000e-04,1.235727e-10,7.560842e-10,2.000000e-05,1.235727e-11,7.560842e-11
157,294.0,0.000500,0.259940,1.143443e-06,5.000000e-04,7.534756e-35,4.610169e-34,2.000000e-04,3.013902e-35,1.844067e-34,2.000000e-05,3.013902e-36,1.844067e-35
158,297.0,0.000500,0.016562,7.285540e-08,5.000000e-04,6.038667e-37,3.694781e-36,2.000000e-04,2.415467e-37,1.477912e-36,2.000000e-05,2.415467e-38,1.477912e-37
159,299.0,0.000500,0.008101,3.563526e-08,5.000000e-04,1.820860e-34,1.114100e-33,2.000000e-04,7.283442e-35,4.456401e-34,2.000000e-05,7.283442e-36,4.456401e-35

### $T_\phi$

In [ ]:
def zeropi_eval(flux=0, truncation=300):
    ncut, phi_cut = 90, 300
    # Define system parameters (in GHz)
    EL = 0.377  # Inductive energy
    EJ = 6.013  # Josephson energy
    EC_phi = 1.142  # Phi mode charging energy
    EC_theta = 0.092  # Theta mode charging energy

    # Compute derived parameters
    E_CJ = 2 * EC_phi
    E_C = 2 / (1 / EC_theta - 1 / EC_phi)

    # Create the grid for the phi coordinate
    phi_grid = scq.Grid1d(-6 * np.pi, 6 * np.pi, phi_cut)

    # Initialize the Zero-Pi qubit system
    zero_pi = scq.ZeroPi(
        grid=phi_grid,
        EJ=EJ,
        EL=EL,
        ECJ=E_CJ,
        EC=E_C,
        dEJ=0.0,
        ng=0.0,
        flux=flux,
        ncut=ncut,
        truncated_dim=truncation,
    )

    # Compute the eigenvalues and construct the Hamiltonian
    evals, _ = zero_pi.eigensys(evals_count=truncation)
    evals = np.sort(evals)
    evals = evals - evals[0]
    return evals

eval_a = zeropi_eval(flux=0)
eval_b = zeropi_eval(flux=0.001)
derivative = [0,]
for i in hspace:
    derivative.append(np.abs(eval_b[i] - eval_a[i]) / 0.001)

In [ ]:
derivative = derivative_theta if drive_theta else derivative_phi
A = 1e-6
w_ir = 1e-9* 2 * np.pi # 1 Hz
t = 10e3 # 10 us = 10e3 ns
gamma_dephase_new = A * np.array(derivative) * np.sqrt(2 * np.abs(np.log(w_ir * t)))
gamma_dephase_new[idx_2] = gamma_dephase_logi
gamma_dephase_new

array([0.00000000e+00, 1.11111111e-04, 7.98860457e-06, 1.19083757e-09,
       4.88206675e-07, 4.56849571e-07, 1.02940459e-08, 2.43799741e-08,
       3.36017969e-08, 2.06765541e-07, 2.69821664e-07, 4.32170170e-07,
       3.18315442e-08, 1.24500583e-05, 1.18087993e-05, 6.08131004e-07,
       3.45262659e-09, 1.32148964e-07, 2.60443126e-08, 8.26769961e-08,
       7.16073802e-07, 2.83246220e-07, 3.31461748e-07, 1.02407867e-08,
       1.87397980e-07, 1.21509913e-07, 1.06525031e-07, 2.35727054e-07,
       2.28208326e-07, 1.30492024e-07, 1.06382933e-07, 4.72534726e-08,
       1.70183660e-07, 1.68907678e-06, 1.51996176e-06, 9.53603980e-08,
       1.20415192e-06, 1.18529837e-06, 9.36671248e-08, 4.56994501e-07,
       4.52585940e-07, 9.99856509e-09, 2.12040625e-07, 4.25521201e-08,
       2.45600444e-09, 1.43790503e-07, 4.40131120e-08, 9.76520418e-08,
       3.68869566e-07, 6.70483818e-08, 9.75980650e-08, 2.38980348e-07,
       3.24469834e-08, 6.36717776e-08, 4.18848750e-08, 1.15782347e-08,
       7.37502730e-06, 1.08126237e-06, 3.04252567e-07, 6.33481836e-06,
       2.28953791e-07, 1.35489046e-07, 1.93849873e-07, 2.60935215e-07,
       1.67949239e-07, 2.93877068e-09, 3.76680104e-08, 5.06926063e-07,
       2.35265246e-07, 1.15283501e-08, 1.00356546e-07, 4.03369759e-08,
       1.87800495e-07, 1.21145494e-07, 8.33267288e-07, 3.72561432e-07,
       1.75859094e-07, 7.08289492e-08, 1.97793030e-07, 1.51761569e-07,
       4.96863994e-08, 1.06954171e-07, 1.93616907e-07, 1.71702724e-07,
       2.34992871e-07, 1.57640753e-07, 2.73865720e-07, 1.86606852e-07,
       1.19821005e-07, 1.55999862e-08, 4.18847516e-08, 4.01866932e-08,
       1.86408509e-07, 1.62077967e-07, 6.97853272e-08, 3.74241368e-07,
       6.19409591e-07, 5.36508626e-07, 8.49931887e-08, 7.01926084e-08,
       1.05397847e-07, 8.47330115e-09, 7.40744652e-08, 7.89972408e-08,
       2.30127849e-08, 2.98900607e-07, 2.83370113e-07, 1.84344290e-07,
       1.48555938e-07, 5.20401888e-08, 1.15714369e-08, 4.04323053e-08,
       7.37892448e-09, 7.71101144e-07, 6.71181519e-07, 2.75371150e-07,
       1.95490169e-07, 1.54401709e-08, 1.46661761e-08, 1.84518581e-07,
       8.39615215e-08, 8.43855576e-08, 4.75175700e-08, 5.78753974e-09,
       2.97083886e-07, 5.91209414e-08, 6.65538863e-08, 3.65477181e-08,
       4.49903211e-08, 5.24266765e-08, 6.20680052e-08, 1.02630282e-07,
       6.77507651e-08, 1.31813820e-07, 8.95672660e-08, 6.21602993e-09,
       2.45434903e-08, 1.20894569e-07, 7.86951617e-08, 1.88517885e-07,
       1.71610484e-08, 3.41280750e-09, 1.84439592e-07, 1.42117005e-07,
       8.99565105e-08, 3.24732848e-09, 3.43602889e-07, 1.74175221e-07,
       8.53764991e-08, 4.97786069e-07, 2.31796432e-07, 2.94895255e-08,
       1.31143308e-07, 7.78711962e-07, 1.24849157e-07, 8.91675473e-07,
       7.08585813e-08, 1.14344332e-06, 7.28553954e-08, 3.56352556e-08])

In [ ]:
np.array(gamma_dephase)

array([0.        , 0.0005    , 0.00011111, 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    , 0.0005    , 0.0005    ,
       0.0005    , 0.0005    , 0.0005    ])